// docs/components.md, drawn from the code so it can never drift: one
// section per role, the engine pins per platform, and a row per profile
// with the pinned model and its facts. `collectComponentsCatalog` reads
// the real modules; `renderComponentsDoc` is pure so a test can feed it
// a scripted catalog. Written by scripts/gen-components-doc.ts and
// drift-checked by scripts/check.sh like docs/api/openapi.json.
import { BUNDLED_RUNTIMES, ENGINE_BINARIES, type BundledRuntime, type EngineBinaryPin } from "@/lib/engineCatalog";
import packageJson from "../../package.json";
import { ROLE_CANDIDATES, STACK_MODELS, type RoleCandidate } from "@/lib/modelCatalog";
import type { CatalogModelLike } from "@/lib/modelStore";
import { PROFILE_TIERS, type ProfileTier } from "@/profiles";
import { ROLE_IDS, ROLES, type RoleId } from "@/roles";

export interface ComponentsCatalog {
  roles: RoleId[];
  labels: Record<string, string>;
  engines: EngineBinaryPin[];
  profiles: ProfileTier[];
  models: CatalogModelLike[];
  candidates: Partial<Record<string, RoleCandidate[]>>;
  runtimes: Array<BundledRuntime & { version: string }>;
  shares?: Partial<Record<string, string>>;
}

export function collectComponentsCatalog(): ComponentsCatalog {
  const shares = Object.fromEntries(ROLE_IDS.flatMap((role) => { const definition = ROLES[role] as { sharesModelWith?: string }; return definition.sharesModelWith ? [[role, definition.sharesModelWith]] : []; }));
  const dependencies = (packageJson as { dependencies?: Record<string, string> }).dependencies ?? {};
  const runtimes = BUNDLED_RUNTIMES.map((runtime) => ({ ...runtime, version: dependencies[runtime.name] ?? "not in package.json" }));
  return { roles: [...ROLE_IDS], labels: Object.fromEntries(ROLE_IDS.map((role) => [role, ROLES[role].label])), engines: ENGINE_BINARIES, profiles: PROFILE_TIERS, models: STACK_MODELS, candidates: ROLE_CANDIDATES, runtimes, shares };
}

const PROFILE_ORDER = ["p16", "p32", "p64", "p128"] as const;
const LLAMA_ROLES = new Set<string>(["chat", "coding", "judge", "router", "vision", "embed"]);

function gb(bytes: number | undefined): string { return !bytes ? "unknown" : bytes < 104_857_600 ? `${(bytes / 1_048_576).toFixed(1)} MB` : `${(bytes / 1_073_741_824).toFixed(2)} GB`; }
function stance(profile: ProfileTier, role: RoleId): string {
  if (profile.resident.includes(role)) return "resident";
  if (profile.onDemand.includes(role)) return "on demand";
  if (profile.installedOnly.includes(role)) return "installed only";
  return "not available";
}
// A pin's minimum profile; a pin that names none or names one that is
// not a tier is treated as needing the largest tier, so a typo can
// never make a model appear to fit every machine.
function minimumProfileIndex(model: CatalogModelLike): number {
  const named = typeof model.sizing === "object" && model.sizing !== null && "profile" in model.sizing ? String((model.sizing as { profile: unknown }).profile) : "";
  const index = PROFILE_ORDER.indexOf(named as typeof PROFILE_ORDER[number]);
  return index < 0 ? PROFILE_ORDER.length - 1 : index;
}
function fits(model: CatalogModelLike, profile: ProfileTier): boolean {
  return PROFILE_ORDER.indexOf(profile.id) >= minimumProfileIndex(model);
}
/** The largest pin that fits: the highest minimum profile, then the
 * biggest file, never the array's order. */
function largest(models: CatalogModelLike[]): CatalogModelLike | undefined {
  return [...models].sort((a, b) => minimumProfileIndex(b) - minimumProfileIndex(a) || (b.download?.approx_bytes ?? 0) - (a.download?.approx_bytes ?? 0))[0];
}
function quantization(model: CatalogModelLike): string {
  const sizing = model.sizing as { quantization?: unknown } | undefined;
  return typeof sizing?.quantization === "string" ? sizing.quantization : "unknown";
}

export function renderComponentsDoc(catalog: ComponentsCatalog): string {
  const lines: string[] = [];
  lines.push("<!-- GENERATED by backend/scripts/gen-components-doc.ts from roles.ts, engineCatalog.ts, profiles.ts and modelCatalog.ts. Do not edit; run `bun run gen:components-doc` in backend/. -->");
  lines.push("# Components inventory");
  lines.push("");
  lines.push("This table is every engine build and model this build of the Stack ships as a pin, per role and per machine profile, drawn from the code by `bun run gen:components-doc` so it cannot drift from what the daemon installs at first run. The tier is the machine profile (`p16` to `p128`, by unified memory on Apple silicon and by VRAM elsewhere), and for each role the Stack picks the largest pinned model that fits the machine's tier. What is available beyond these pins is the Catalog's business: its signed engine index (`getmaipai/catalog`, `engines/index.json`, STACK-97) is what the updates route reads for engines, and its model index will do the same for models; a role with no pin here lists its candidates from `dev.md` and the backlog, or says not yet.");
  lines.push("");
  for (const role of catalog.roles) {
    lines.push(`## ${role} (${catalog.labels[role] ?? role})`);
    lines.push("");
    const shares = catalog.shares?.[role];
    if (shares) { lines.push(`Shares \`${shares}\`'s model and process unless bound elsewhere; the rows below are \`${shares}\`'s pins seen from this role.`); lines.push(""); }
    lines.push("Engines per platform:");
    lines.push("");
    lines.push("| Engine | Build | Platform | Status |");
    lines.push("|---|---|---|---|");
    const pins = LLAMA_ROLES.has(role) ? catalog.engines : [];
    for (const pin of pins) lines.push(`| \`${pin.id}\` | ${pin.tag} | ${pin.platform} ${pin.arch}${pin.requiresNvidia ? " (NVIDIA)" : ""} | ${pin.verified ? "pinned, verified" : "pinned, not yet verified"} |`);
    const modelRole = shares ?? role;
    const runtimes = catalog.runtimes.filter((runtime) => runtime.roles.includes(modelRole));
    for (const runtime of runtimes) lines.push(`| \`${runtime.name}\` | ${runtime.version} | ${runtime.platforms} | bundled with the Stack (backend/package.json and the lockfile; updates with the Stack's release and the monthly dependency sweep, never the engine index) |`);
    const engineCandidates = (catalog.candidates[modelRole] ?? []).filter((candidate) => candidate.kind === "engine");
    for (const candidate of engineCandidates) lines.push(`| ${candidate.name} | | | candidate (${candidate.source}) |`);
    if (pins.length === 0 && runtimes.length === 0 && engineCandidates.length === 0) lines.push("| | | | not yet |");
    lines.push("");
    lines.push("| Profile | Stance | Model | Quantization | File size | Measured footprint | Measured context | Licence | Source | Status |");
    lines.push("|---|---|---|---|---|---|---|---|---|---|");
    const pinned = catalog.models.filter((model) => model.role === modelRole && model.download?.sha256 && !model.component);
    const components = catalog.models.filter((model) => model.role === modelRole && model.download?.sha256 && model.component);
    const modelCandidates = (catalog.candidates[modelRole] ?? []).filter((candidate) => candidate.kind === "model");
    for (const profile of catalog.profiles) {
      const roleStance = stance(profile, role);
      // A tier where the role does not exist installs nothing for it,
      // whatever chat's pin says.
      if (roleStance === "not available") { lines.push(`| ${profile.id} | not available |  |  |  |  |  |  |  | not available |`); continue; }
      const model = largest(pinned.filter((candidate) => fits(candidate, profile)));
      const measured = model?.measured;
      const status = model ? "pinned" : modelCandidates.length > 0 ? `candidate (${modelCandidates.map((candidate) => candidate.name).join(", ")})` : "not yet";
      lines.push(`| ${profile.id} | ${roleStance} | ${model ? `\`${model.id}\`` : ""} | ${model ? quantization(model) : ""} | ${model ? gb(model.download?.approx_bytes) : ""} | ${measured ? `${gb(measured.footprintBytes)} (${measured.hardware})` : model ? "not measured" : ""} | ${measured ? (measured.contextLength > 0 ? String(measured.contextLength) : "n/a") : model ? "not measured" : ""} | ${model?.license ?? ""} | ${model ? `${model.repo ?? "catalog"} @ ${model.revision ?? "unknown"}` : ""} | ${status} |`);
    }
    if (components.length) {
      lines.push("");
      lines.push(`Installed beside the model, never selected on its own: ${components.map((component) => `\`${component.id}\` (${component.component}, ${gb(component.download?.approx_bytes)}, ${component.license ?? "licence unknown"}, ${component.repo ?? "catalog"} @ ${component.revision ?? "unknown"})`).join("; ")}.`);
    }
    lines.push("");
  }
  return lines.join("\n");
}
