import { createRoute, z } from "@hono/zod-openapi";
import { apiRouter, ErrorSchema, idParamSchema } from "@/lib/openapi";
import { requireClientOrOperator } from "@/lib/clients";
import { showroom, showroomGroups } from "@/showroom/fixture";

const GroupSchema = z.object({ id: z.string(), name: z.string(), parentId: z.string().nullable(), modelCount: z.number().int(), bytesOnDisk: z.number().int(), memoryBytes: z.number().int(), usage: z.object({ requests: z.number().int(), tokens: z.number().int() }), status: z.object({ loaded: z.number().int(), ready: z.number().int(), onDemand: z.number().int(), failed: z.number().int() }), worstHealth: z.string().nullable() });
const listRoute = createRoute({ method: "get", path: "/", tags: ["Groups"], summary: "List model groups", middleware: [requireClientOrOperator] as const, responses: { 200: { content: { "application/json": { schema: z.object({ groups: z.array(GroupSchema) }) } }, description: "Model groups and rollups." } } });
const actionRoute = createRoute({ method: "post", path: "/{id}/actions", tags: ["Groups"], summary: "Apply a group action", middleware: [requireClientOrOperator] as const, request: { params: idParamSchema("id"), body: { content: { "application/json": { schema: z.object({ action: z.string() }) } } } }, responses: { 200: { content: { "application/json": { schema: z.object({ ok: z.literal(true), action: z.string(), modelCount: z.number().int() }) } }, description: "Group action accepted." }, 404: { content: { "application/json": { schema: ErrorSchema } }, description: "Unknown group." } } });
const renameRoute = createRoute({ method: "patch", path: "/{id}", tags: ["Groups"], summary: "Rename or move a model group", middleware: [requireClientOrOperator] as const, request: { params: idParamSchema("id"), body: { content: { "application/json": { schema: z.object({ name: z.string().min(1), parentId: z.string().nullable().optional() }) } } } }, responses: { 200: { content: { "application/json": { schema: GroupSchema } }, description: "Updated model group." }, 404: { content: { "application/json": { schema: ErrorSchema } }, description: "Unknown group." } } });
export const groupsRoutes = apiRouter();
groupsRoutes.openapi(listRoute, (c) => c.json({ groups: showroom() ? showroomGroups : [] } as never, 200));
groupsRoutes.openapi(actionRoute, (c) => { const id = c.req.valid("param").id; const group = showroomGroups.find((item) => item.id === id); if (!group) return c.json({ error: "Unknown group" }, 404); return c.json({ ok: true as const, action: c.req.valid("json").action, modelCount: group.modelCount }, 200); });
groupsRoutes.openapi(renameRoute, (c) => { const group = showroomGroups.find((item) => item.id === c.req.valid("param").id); if (!group) return c.json({ error: "Unknown group" }, 404); const body = c.req.valid("json"); group.name = body.name; if (body.parentId !== undefined) group.parentId = body.parentId; return c.json(group as never, 200); });
