import { useEffect, useState } from "react";
import { Area, AreaChart, CartesianGrid, ReferenceArea, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Link } from "react-router-dom";
import { toast } from "sonner";
import { api, type BudgetResponse, type HardwareResponse, type HealthItem, type NotificationRecord, type RoleRecord, type SpeedResult } from "@/lib/api";
import { useApiResource } from "@/lib/useApiResource";
import { displayName } from "@/lib/names";
import { getIcon } from "@/kit/icons";
import { Card, CardContent, CardHeader, CardTitle } from "@/kit/ui/card";
import { Checkbox } from "@/kit/ui/checkbox";
import { ToggleGroup, ToggleGroupItem } from "@/kit/ui/toggle-group";
import { Toaster } from "@/kit/ui/sonner";
import { RelativeTime } from "@/kit/ui/relative-time";
import { ActivityList } from "./overview/ActivityList";
import { ClientsList } from "./overview/ClientsList";
import { FactsColumn } from "./overview/FactsColumn";
import { HeadroomScale, StorageBar } from "./overview/SegmentedBar";
import { StatusStrip } from "./overview/StatusStrip";
import { TileStrip, type Tile } from "./overview/TileStrip";
import type { ActivityItem, Range, SeriesResponse, SeriesSample, StorageResponse, UpdatesResponse } from "./overview/types";

type Layout = "desktop" | "tablet" | "phone";
type CountResponse = { models?: Array<{ id: string; name?: string; sizeBytes?: number }>; clients?: Array<{ id: string; name?: string; requests?: number; lastSeenAt?: string; revokedAt?: string | null }>; engines?: Array<{ id: string; label?: string; name?: string }> };
const abilityLegend = [{ id: "chat", label: "Chat", color: "bg-orange-500" }, { id: "voice", label: "Voice", color: "bg-cyan-500" }, { id: "image", label: "Images", color: "bg-violet-500" }, { id: "video", label: "Video", color: "bg-blue-500" }, { id: "music", label: "Music", color: "bg-emerald-500" }];
const Check = getIcon("Check");

function labelFor(at: string | number): string { return new Date(at).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }); }
function initialRange(): Range { const saved = typeof window === "undefined" ? null : window.localStorage.getItem("maipai-overview-range"); return saved === "hour" || saved === "day" || saved === "week" || saved === "month" ? saved : "day"; }
function layoutFor(width: number): Layout { return width >= 1200 ? "desktop" : width >= 640 ? "tablet" : "phone"; }
function formatBytes(bytes: number): string { if (bytes < 1_000_000_000) return `${Math.round(bytes / 1_000_000)} MB`; if (bytes < 1_000_000_000_000) return `${(bytes / 1_000_000_000).toFixed(1)} GB`; return `${(bytes / 1_000_000_000_000).toFixed(1)} TB`; }
function useLayout(): Layout { const [layout, setLayout] = useState<Layout>(() => layoutFor(typeof window === "undefined" ? 1440 : window.innerWidth)); useEffect(() => { const update = () => setLayout(layoutFor(window.innerWidth)); update(); window.addEventListener("resize", update); return () => window.removeEventListener("resize", update); }, []); return layout; }

export function formatSpeedSentence(latest: SpeedResult | undefined, previous: SpeedResult | undefined): string {
  if (!latest?.tokensPerSecond) return "No speed test has been recorded yet.";
  const model = latest.modelId ?? "the resident chat model";
  const build = latest.engine ? ` (${latest.engine})` : "";
  return `Your Mac: ${latest.tokensPerSecond} tokens per second on ${model}${build}${previous?.tokensPerSecond ? `, was ${previous.tokensPerSecond} before ${latest.engine ?? "the last engine update"}` : ""}.`;
}
function speedDisplaySentence(latest: SeriesSample | undefined, previous: SeriesSample | undefined): string { if (!latest?.tokensPerSecond) return "No speed test has been recorded yet."; const model = displayName(latest.modelId ?? "the resident chat model"); const build = latest.engine ? ` on ${displayName(latest.engine)}` : ""; return `${latest.tokensPerSecond} tokens per second on ${model}${build}${previous?.tokensPerSecond ? `, up from ${previous.tokensPerSecond}` : ""}.`; }

function HeroChart({ usage, memory, speed, range, setRange, metric, setMetric, visibleAbilities, setVisibleAbilities, hardware, budget }: { usage: SeriesSample[]; memory: SeriesSample[]; speed: SeriesSample[]; range: Range; setRange: (value: Range) => void; metric: "usage" | "memory" | "speed"; setMetric: (value: "usage" | "memory" | "speed") => void; visibleAbilities: Record<string, boolean>; setVisibleAbilities: (value: Record<string, boolean>) => void; hardware?: { proposed?: { speedRange?: { min: number; max: number }; id: string } | null }; budget?: BudgetResponse }) {
  const tab = metric;
  const rangeMs = { hour: 60 * 60_000, day: 24 * 60 * 60_000, week: 7 * 24 * 60 * 60_000, month: 30 * 24 * 60 * 60_000 }[range];
  const end = Date.now(); const start = end - rangeMs;
  const usageData = usage.filter((item) => visibleAbilities[item.ability === "stt" || item.ability === "tts" ? "voice" : item.ability ?? "chat"] !== false).map((item) => ({ ...item, timestamp: Date.parse(item.at), label: labelFor(item.at), tokens: (item.tokensIn ?? 0) + (item.tokensOut ?? 0) }));
  const memoryData = memory.map((item) => ({ ...item, timestamp: Date.parse(item.at), label: labelFor(item.at), free: Math.round((item.freeBytes ?? 0) / 1_073_741_824 * 10) / 10 }));
  const speedData = speed.map((item) => ({ ...item, timestamp: Date.parse(item.at), label: labelFor(item.at), tps: item.tokensPerSecond ?? 0 }));
  const data = (tab === "usage" ? usageData : tab === "memory" ? memoryData : speedData) as Array<{ timestamp: number; label: string; requests?: number; tokens?: number; free?: number; tps?: number }>;
  const sentence = tab === "usage" ? "Usage is measured across the selected range." : tab === "memory" ? (budget?.pressure === "normal" ? "Memory headroom is good" : "Memory pressure is high") : speedDisplaySentence(speed.at(-1), speed.at(-2));
  return <Card data-widget data-hero-chart data-axis-start={String(start)} data-axis-end={String(end)}><CardHeader className="pb-3"><div className="flex flex-wrap items-center justify-between gap-3"><CardTitle className="text-base">Overview</CardTitle><ToggleGroup type="single" value={tab} onValueChange={(value) => { if (value) setMetric(value as typeof tab); }} variant="outline" size="sm" aria-label="Chart metric"><ToggleGroupItem value="usage">Usage</ToggleGroupItem><ToggleGroupItem value="memory">Memory</ToggleGroupItem><ToggleGroupItem value="speed">Speed</ToggleGroupItem></ToggleGroup></div></CardHeader><CardContent><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap items-center gap-2">{tab === "usage" && abilityLegend.map((ability) => <label className="flex items-center gap-1.5 text-xs text-muted-foreground" key={ability.id}><Checkbox aria-label={ability.label} className="size-3.5" checked={visibleAbilities[ability.id] !== false} onCheckedChange={(checked) => setVisibleAbilities({ ...visibleAbilities, [ability.id]: checked === true })} /><span className={`size-2 rounded-full ${ability.color}`} />{ability.label}</label>)}</div><ToggleGroup type="single" value={range} onValueChange={(value) => { if (value) setRange(value as Range); }} variant="outline" size="sm" aria-label="Time range"><ToggleGroupItem value="hour" aria-label="1h">1h</ToggleGroupItem><ToggleGroupItem value="day" aria-label="1D">1D</ToggleGroupItem><ToggleGroupItem value="week" aria-label="1W">1W</ToggleGroupItem><ToggleGroupItem value="month" aria-label="1M">1M</ToggleGroupItem></ToggleGroup></div><div className="h-[200px] sm:h-[220px] lg:h-[280px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><CartesianGrid strokeDasharray="3 3" className="stroke-border" /><XAxis dataKey="timestamp" type="number" domain={[start, end]} tickFormatter={(value) => labelFor(value)} /><YAxis /><Tooltip labelFormatter={(value) => labelFor(Number(value))} />{tab === "usage" && <><Area type="monotone" dataKey="requests" name="Requests" stroke="hsl(22 99% 50%)" fill="hsl(22 99% 50% / .16)" /><Area type="monotone" dataKey="tokens" name="Tokens" stroke="hsl(190 90% 40%)" fill="hsl(190 90% 40% / .10)" /></>}{tab === "memory" && <Area type="monotone" dataKey="free" name="Free GB" stroke="hsl(190 90% 40%)" fill="hsl(190 90% 40% / .14)" />}{tab === "speed" && <>{hardware?.proposed?.speedRange && <ReferenceArea y1={hardware.proposed.speedRange.min} y2={hardware.proposed.speedRange.max} fill="hsl(190 90% 40% / .12)" strokeOpacity={0} />}<Area type="monotone" dataKey="tps" name="Tokens/s" stroke="hsl(22 99% 50%)" fill="hsl(22 99% 50% / .14)" /></>}</AreaChart></ResponsiveContainer></div><div data-status-sentence className="mt-3 flex items-center gap-2 text-sm"><Check className="size-4 text-emerald-600" />{sentence}</div></CardContent></Card>;
}

function HealthCard({ items }: { items: HealthItem[] }) { if (!items.length) return null; return <Card data-widget><CardHeader className="pb-3"><CardTitle className="text-base">Health</CardTitle></CardHeader><CardContent className="divide-y p-0">{items.slice(0, 4).map((item) => <Link className="block px-5 py-3 hover:bg-muted/40" to="/alerts" key={item.code}><div className="text-sm font-medium">{item.title}</div><div className="mt-1 text-xs text-muted-foreground"><RelativeTime at={item.since} /> · {item.text}</div></Link>)}</CardContent></Card>; }
function PhoneOverview({ status, hero, models, engines, facts, activity }: { status: React.ReactNode; hero: React.ReactNode; models: React.ReactNode; engines: React.ReactNode; facts: React.ReactNode; activity: React.ReactNode }) { return <main className="mx-auto grid w-full max-w-7xl grid-cols-1 gap-5 px-4 py-5" data-layout="phone"><div>{status}</div>{hero}{models}{engines}{facts}{activity}</main>; }

export function OverviewPage() {
  const layout = useLayout(); const [range, setRange] = useState<Range>(initialRange); const [speedTesting, setSpeedTesting] = useState(false); const [visibleAbilities, setVisibleAbilities] = useState<Record<string, boolean>>(() => Object.fromEntries(abilityLegend.map((ability) => [ability.id, true])));
  const roles = useApiResource<{ roles: RoleRecord[] }>("/stack/v1/roles"); const budget = useApiResource<BudgetResponse>("/stack/v1/budget"); const hardware = useApiResource<HardwareResponse>("/stack/v1/hardware"); const healthz = useApiResource<{ version: string; uptimeSeconds: number }>("/healthz"); const health = useApiResource<{ health: HealthItem[] }>("/stack/v1/health"); const notifications = useApiResource<{ notifications: NotificationRecord[] }>("/stack/v1/notifications?durable=1"); const engines = useApiResource<CountResponse>("/stack/v1/engines"); const models = useApiResource<CountResponse>("/stack/v1/models"); const clients = useApiResource<CountResponse>("/stack/v1/clients"); const updates = useApiResource<UpdatesResponse>("/stack/v1/updates"); const storage = useApiResource<StorageResponse>("/stack/v1/storage");
  const [metric, setMetric] = useState<"usage" | "memory" | "speed">("usage"); const apiRange = range === "month" ? "week" : range; const series = useApiResource<SeriesResponse>(`/stack/v1/series?range=${apiRange}&window=${range}&metric=${metric}`); useEffect(() => { window.localStorage.setItem("maipai-overview-range", range); }, [range]);
  const roleRows = roles.data?.roles ?? []; const healthRows = health.data?.health ?? []; const activityItems: ActivityItem[] = (notifications.data?.notifications ?? []).slice(0, 5).map((item) => ({ id: item.id, primary: displayName(item.title), at: item.at })); const usage = series.data?.usage ?? []; const memory = series.data?.memory ?? []; const speed = series.data?.speed ?? [];
  const modelTiles: Tile[] = (models.data?.models ?? []).slice(0, 8).map((model) => ({ id: model.id, name: displayName(model.name ?? model.id), title: model.sizeBytes ? formatBytes(model.sizeBytes) : model.id, href: `/models?model=${encodeURIComponent(model.id)}` })); const engineTiles: Tile[] = (engines.data?.engines ?? []).slice(0, 8).map((engine) => ({ id: engine.id, name: displayName(engine.label ?? engine.name ?? engine.id), href: `/engines?engine=${encodeURIComponent(engine.id)}` }));
  async function runSpeedTestNow(): Promise<void> { setSpeedTesting(true); try { await api.post<{ result: SpeedResult }>("/stack/v1/speed-test"); await series.refetch(); } catch (error) { toast.error(error instanceof Error ? error.message : "The speed test failed."); } finally { setSpeedTesting(false); } }
  const status = <StatusStrip roles={roleRows} budget={budget.data} health={healthRows} engineCount={engines.data?.engines?.length ?? 0} />; const hero = <HeroChart usage={usage} memory={memory} speed={speed} range={range} setRange={setRange} metric={metric} setMetric={setMetric} visibleAbilities={visibleAbilities} setVisibleAbilities={setVisibleAbilities} hardware={hardware.data} budget={budget.data} />; const facts = <FactsColumn hardware={hardware.data?.hardware} healthz={healthz.data} budget={budget.data} updates={updates.data} counts={{ engines: engines.data?.engines?.length ?? 0, models: models.data?.models?.length ?? 0, clients: clients.data?.clients?.length ?? 0 }} speedTesting={speedTesting} onSpeedTest={() => void runSpeedTestNow()} />; const modelsStrip = <TileStrip title="Models" tiles={modelTiles} empty="No models are installed yet." />; const enginesStrip = <TileStrip title="Engines" tiles={engineTiles} empty="No engines are installed yet." />;
  const left = <div className="space-y-5">{healthRows.length > 0 && <HealthCard items={healthRows} />}{facts}<ClientsList clients={clients.data?.clients ?? []} /><ActivityList items={activityItems} /></div>; const wide = <div className="min-w-0 space-y-5">{status}{hero}{modelsStrip}{enginesStrip}<div className="grid gap-5 lg:grid-cols-2"><StorageBar values={storage.data?.byCategory ?? {}} free={storage.data?.freeDiskBytes} /><HeadroomScale availablePercent={budget.data?.availablePercent} pressure={budget.data?.pressure} /></div></div>;
  if (layout === "phone") return <><Toaster /><PhoneOverview status={status} hero={hero} models={modelsStrip} engines={enginesStrip} facts={facts} activity={<ActivityList items={activityItems} />} /></>;
  const layoutClass = layout === "desktop" ? "lg:grid-cols-12" : "sm:grid-cols-1"; return <><Toaster /><main className="mx-auto w-full max-w-7xl px-4 py-5 sm:px-8 lg:px-10 lg:py-6"><div data-layout={layout} className={`grid gap-5 ${layoutClass}`}><aside className={layout === "desktop" ? "lg:col-span-3" : ""}>{left}</aside><section className={layout === "desktop" ? "min-w-0 lg:col-span-9" : "min-w-0"}>{wide}</section></div></main></>;
}
