import { useState } from "react";
import type { ReactNode } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Link } from "react-router-dom";
import type { BudgetResponse, HealthItem, NotificationRecord, RoleRecord } from "@/lib/api";
import { useApiResource } from "@/lib/useApiResource";
import { Badge } from "@/kit/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/kit/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/kit/ui/select";

type Range = "hour" | "day" | "week";
type SeriesSample = { at: string; requests?: number; tokensIn?: number; tokensOut?: number; freeBytes?: number; availablePercent?: number; pressure?: string; firstTokenMs?: number | null; tokensPerSecond?: number | null };
type SeriesResponse = { range: Range; usage: SeriesSample[]; memory: SeriesSample[]; speed: SeriesSample[] };

function formatBytes(bytes: number): string { if (bytes < 1_000_000_000) return `${Math.round(bytes / 1_000_000)} MB`; return `${(bytes / 1_000_000_000).toFixed(1)} GB`; }
function labelFor(at: string): string { return new Date(at).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }); }
function Widget({ title, description, children, className = "" }: { title: string; description?: string; children: ReactNode; className?: string }) { return <Card className={className}><CardHeader className="pb-3"><CardTitle className="text-base">{title}</CardTitle>{description && <CardDescription>{description}</CardDescription>}</CardHeader><CardContent>{children}</CardContent></Card>; }

export function OverviewPage() {
  const [range, setRange] = useState<Range>("day");
  const roles = useApiResource<{ roles: RoleRecord[] }>("/stack/v1/roles");
  const budget = useApiResource<BudgetResponse>("/stack/v1/budget");
  const health = useApiResource<{ health: HealthItem[] }>("/stack/v1/health");
  const notifications = useApiResource<{ notifications: NotificationRecord[] }>("/stack/v1/notifications");
  const series = useApiResource<SeriesResponse>(`/stack/v1/series?range=${range}`);
  const roleRows = roles.data?.roles ?? [];
  const ready = roleRows.filter((role) => role.state === "ready").length;
  const attention = (health.data?.health ?? []).length;
  const usage = (series.data?.usage ?? []).map((item) => ({ ...item, label: labelFor(item.at), tokens: (item.tokensIn ?? 0) + (item.tokensOut ?? 0) }));
  const memory = (series.data?.memory ?? []).map((item) => ({ ...item, label: labelFor(item.at), free: Math.round((item.freeBytes ?? 0) / 1_073_741_824 * 10) / 10 }));
  const speed = (series.data?.speed ?? []).map((item) => ({ ...item, label: labelFor(item.at), tps: item.tokensPerSecond ?? 0 }));
  const ringLinks = [{ label: "Ready", value: ready, href: "/models?state=ready", tone: "default" as const }, { label: "Roles", value: roleRows.length, href: "/engines", tone: "secondary" as const }, { label: "Attention", value: attention, href: "/alerts", tone: attention ? "destructive" as const : "secondary" as const }];
  return <main className="mx-auto w-full max-w-7xl space-y-7 px-4 py-7 sm:px-8 lg:px-10 lg:py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-primary">MaiPai Stack</p><h2 className="mt-1 text-3xl font-semibold tracking-tight">Overview</h2><p className="mt-2 text-base text-muted-foreground">A measured view of this computer, its abilities, and what the Stack has been doing.</p></div><Select value={range} onValueChange={(value) => setRange(value as Range)}><SelectTrigger className="w-32" aria-label="Time range"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="hour">Last hour</SelectItem><SelectItem value="day">Last day</SelectItem><SelectItem value="week">Last week</SelectItem></SelectContent></Select></div>
    <div className="grid gap-4 md:grid-cols-3">{ringLinks.map((ring) => <Link to={ring.href} key={ring.label} className="block transition hover:-translate-y-0.5"><Card className="h-full"><CardContent className="flex items-center gap-4 p-5"><div className="flex size-16 items-center justify-center rounded-full border-[6px] border-primary/30 text-xl font-semibold">{ring.value}</div><div><p className="font-medium">{ring.label}</p><Badge className="mt-2" variant={ring.tone}>{ring.label === "Attention" && ring.value === 0 ? "All clear" : ring.label === "Roles" ? "Serving locally" : "Available now"}</Badge></div></CardContent></Card></Link>)}</div>
    <div className="grid gap-5 lg:grid-cols-2"><Widget title="Usage" description="Requests and tokens served in the selected range."><div className="h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={usage}><CartesianGrid strokeDasharray="3 3" className="stroke-border" /><XAxis dataKey="label" /><YAxis /><Tooltip /><Area type="monotone" dataKey="requests" name="Requests" stroke="hsl(22 99% 50%)" fill="hsl(22 99% 50% / .16)" /><Area type="monotone" dataKey="tokens" name="Tokens" stroke="hsl(190 90% 40%)" fill="hsl(190 90% 40% / .10)" /></AreaChart></ResponsiveContainer></div></Widget><Widget title="Memory" description="Free memory and pressure from the kernel ledger."><div className="h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={memory}><CartesianGrid strokeDasharray="3 3" className="stroke-border" /><XAxis dataKey="label" /><YAxis unit=" GB" /><Tooltip /><Area type="monotone" dataKey="free" name="Free GB" stroke="hsl(190 90% 40%)" fill="hsl(190 90% 40% / .14)" /></AreaChart></ResponsiveContainer></div><p className="mt-2 text-sm text-muted-foreground">{budget.data ? `${formatBytes(budget.data.freeMemoryBytes)} free now · ${budget.data.pressure} pressure` : "Waiting for the memory ledger."}</p></Widget></div>
    <div className="grid gap-5 lg:grid-cols-3"><Widget title="Speed" description="Latest local chat throughput."><div className="h-44"><ResponsiveContainer width="100%" height="100%"><AreaChart data={speed}><CartesianGrid strokeDasharray="3 3" className="stroke-border" /><XAxis dataKey="label" /><YAxis unit=" t/s" /><Tooltip /><Area type="monotone" dataKey="tps" name="Tokens/s" stroke="hsl(22 99% 50%)" fill="hsl(22 99% 50% / .14)" /></AreaChart></ResponsiveContainer></div></Widget><Widget title="Loaded now" description="Resident work stays visible and measured."><div className="space-y-3">{(budget.data?.loaded ?? []).slice(0, 4).map((item) => <div className="flex items-center justify-between gap-3" key={item.id}><span className="truncate text-sm">{item.id}</span><span className="text-sm text-muted-foreground">{formatBytes(item.peakBytes)}</span></div>)}{!budget.data?.loaded.length && <p className="text-sm text-muted-foreground">Nothing is loaded yet.</p>}</div></Widget><Widget title="Recent activity" description="The last things the Stack noticed."><div className="space-y-3">{(notifications.data?.notifications ?? []).slice(0, 4).map((item) => <div key={item.id}><p className="text-sm">{item.title}</p><p className="text-xs text-muted-foreground">{new Date(item.at).toLocaleDateString()}</p></div>)}{!notifications.data?.notifications.length && <p className="text-sm text-muted-foreground">No notifications yet.</p>}</div></Widget></div>
    <div className="grid gap-5 lg:grid-cols-2"><Widget title="Health" description="One clear next step per issue."><div className="space-y-3">{(health.data?.health ?? []).slice(0, 3).map((item) => <div className="flex items-center justify-between gap-3" key={item.code}><div><p className="text-sm font-medium">{item.title}</p><p className="text-sm text-muted-foreground">{item.text}</p></div><Link className="text-sm underline" to={item.learnMore ?? "/alerts"}>{item.fix?.label ?? "Learn more"}</Link></div>)}{!health.data?.health.length && <p className="text-sm text-muted-foreground">No repairs needed.</p>}</div></Widget><Widget title="This computer" description="The measured machine underneath the console."><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">{budget.data ? `${Math.round(budget.data.capBytes / 1_073_741_824)} GB memory budget` : "Memory budget loading"}</p><p className="text-sm text-muted-foreground">Plans and hardware details stay on the board.</p></div><Link className="text-sm underline" to="/abilities">Add abilities</Link></div></Widget></div>
  </main>;
}
