import { useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import type { EngineSetting } from "@/lib/api";
import { api } from "@/lib/api";
import { useApiResource } from "@/lib/useApiResource";
import { GenericForm } from "@/kit/settings/GenericForm";
import { Button } from "@/kit/ui/button";
import type { SectionFrameComponent } from "@/pages/DashboardShell";

export function SettingsPage({ Frame }: { Frame: SectionFrameComponent }) {
  const settings = useApiResource<{ settings: EngineSetting[] }>("/stack/v1/settings");
  const [draft, setDraft] = useState<Record<string, string | number | boolean>>({});
  useEffect(() => { if (settings.data) setDraft(Object.fromEntries(settings.data.settings.map((setting) => [setting.key, setting.pending ?? setting.inEffect]))); }, [settings.data]);
  const location = useLocation();
  const [pending, setPending] = useState<string[]>([]);
  const sections = useMemo(() => [{ id: "general", title: "General" }, { id: "updates", title: "Updates" }, { id: "backups", title: "Backups" }, { id: "network", title: "Network and access" }, { id: "channels", title: "Alert channels" }, { id: "storage", title: "Storage" }, { id: "maintenance", title: "Maintenance" }, { id: "engines", title: "Engines" }, { id: "hardware", title: "Hardware" }, { id: "diagnostics", title: "Diagnostics" }, { id: "reset", title: "Reset" }], []);
  async function changeSetting(key: string, value: string | number | boolean): Promise<void> { const next = { ...draft, [key]: value }; setDraft(next); const changed = settings.data?.settings.find((setting) => setting.key === key); if (changed?.needsRestart) setPending((current) => current.includes(key) ? current : [...current, key]); try { await api.put("/stack/v1/settings", next); await settings.refetch(); } catch { /* the row keeps its draft until the next retry */ } }
  const active = location.hash.replace("#", "") || "general";
  return <Frame title="Settings" description="The few declared settings for this local Stack."><div className="grid gap-6 lg:grid-cols-[14rem_1fr]"><aside className="space-y-3"><label className="block text-sm font-medium">Find a setting<input className="mt-2 h-9 w-full rounded-md border bg-background px-3 text-sm" placeholder="Find a setting" /></label><nav className="space-y-1">{sections.map((section) => <a className={`block rounded-md px-3 py-2 text-sm ${active === section.id ? "bg-muted font-medium" : "text-muted-foreground hover:bg-muted"}`} href={`#${section.id}`} key={section.id}>{section.title}</a>)}</nav></aside><div className="space-y-5">{settings.loading && <p className="text-sm text-muted-foreground">Loading declared settings…</p>}{settings.error && <p className="text-sm text-destructive">Settings could not be loaded.</p>}{settings.data && <><section id="general" className="scroll-mt-6 rounded-xl border p-5"><h2 className="font-semibold">General</h2><p className="mt-1 text-sm text-muted-foreground">How this Stack presents itself.</p><div className="mt-4"><GenericForm settings={settings.data.settings} values={draft} onChange={(key, value) => void changeSetting(key, value)} /></div></section><section id="updates" className="scroll-mt-6 rounded-xl border p-5"><h2 className="font-semibold">Updates</h2><p className="mt-1 text-sm text-muted-foreground">Updates are checked on request. Installed builds stay in control of this computer.</p></section><section id="backups" className="scroll-mt-6 rounded-xl border p-5"><h2 className="font-semibold">Backups</h2><p className="mt-1 text-sm text-muted-foreground">Backups arrive with STACK-11.</p></section><section id="network" className="scroll-mt-6 rounded-xl border p-5"><h2 className="font-semibold">Network and access</h2><p className="mt-1 text-sm text-muted-foreground"><Link className="text-primary underline" to="/access">Manage Clients and LAN access</Link>.</p></section>{sections.slice(4).map((section) => <section id={section.id} className="scroll-mt-6 rounded-xl border p-5" key={section.id}><h2 className="font-semibold">{section.title}</h2><p className="mt-1 text-sm text-muted-foreground">This section is declared by the Stack and stays local to this computer.</p></section>)}{pending.length > 0 && <div className="sticky bottom-4 flex items-center justify-between gap-4 rounded-xl border bg-card p-4 shadow-sm"><span>{pending.length} change{pending.length === 1 ? "" : "s"} need a restart of the chat engine</span><div className="flex gap-2"><Button variant="outline" onClick={() => setPending([])}>Discard</Button><Button onClick={() => setPending([])}>Apply now</Button></div></div>}</>}</div></div></Frame>;
}
