import { FormEvent, useMemo, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { getIcon } from "@/kit/icons";
import { api, type RoleRecord } from "@/lib/api";
import { useApiResource } from "@/lib/useApiResource";
import { useStackChat } from "@/lib/useStackChat";
import { labelForRole } from "@/lib/modelStates";
import { Badge } from "@/kit/ui/badge";
import { Button } from "@/kit/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/kit/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/kit/ui/dialog";
import { Input } from "@/kit/ui/input";
import { Message, MessageContent, MessageFooter, MessageGroup, MessageHeader } from "@/kit/ui/message";
import { MessageScroller, MessageScrollerContent, MessageScrollerItem, MessageScrollerProvider, MessageScrollerViewport } from "@/kit/ui/message-scroller";
import { Bubble, BubbleContent } from "@/kit/ui/bubble";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/kit/ui/tabs";

const Mic = getIcon("Mic"); const Send = getIcon("Send"); const Square = getIcon("Square"); const Volume2 = getIcon("Volume2");
const READY = new Set(["ready", "busy"]);

function roleReady(role?: RoleRecord): boolean { return !!role && (READY.has(role.state) || role.id === "chat"); }

function OfflineState({ role, labelOf }: { role: RoleRecord; labelOf: (id: string) => string }) {
  const actionLabel = role.id === "tts" ? "Speak" : role.id === "stt" ? "Listen" : labelOf(role.id);
  return <Card><CardContent className="space-y-3 p-6"><Badge variant="outline">Not ready</Badge><p className="font-medium">{actionLabel} is not ready yet.</p><p className="text-base text-muted-foreground">{role.reason ?? "Engine binding is not implemented yet."}</p><Button variant="outline" asChild><Link to="/">Back to the board</Link></Button></CardContent></Card>;
}

function ChatTab({ role, labelOf }: { role: RoleRecord; labelOf: (id: string) => string }) {
  const { messages, status, error, send, stop } = useStackChat(); const [draft, setDraft] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!draft.trim()) return; const next = draft; setDraft(""); await send(next); }
  return <Card className="overflow-hidden"><CardHeader><CardTitle>Chat with your local AI</CardTitle><CardDescription>Nothing is saved. Send a sentence and watch the reply arrive.</CardDescription></CardHeader><CardContent className="space-y-4"><MessageScrollerProvider autoScroll defaultScrollPosition="end"><MessageScroller className="h-[28rem] rounded-xl border bg-muted/20"><MessageScrollerViewport><MessageScrollerContent className="gap-5 p-4">{messages.length === 0 && <MessageScrollerItem><p className="p-6 text-center text-base text-muted-foreground">Say hello in one sentence.</p></MessageScrollerItem>}{messages.map((message) => <MessageScrollerItem key={message.id}><MessageGroup><Message align={message.role === "user" ? "end" : "start"}><MessageContent><MessageHeader>{message.role === "user" ? "You" : "MaiPai Stack"}</MessageHeader><Bubble align={message.role === "user" ? "end" : "start"} variant={message.role === "user" ? "default" : "secondary"}><BubbleContent>{message.content || (status === "streaming" ? "Thinking…" : "")}</BubbleContent></Bubble>{message.error && <MessageFooter className="text-destructive">{message.error}</MessageFooter>}{message.metrics && <MessageFooter>{message.metrics.engine} · {message.metrics.model} · {message.metrics.firstTokenMs === null ? "no first token" : `${message.metrics.firstTokenMs} ms first token`} · {message.metrics.tokensPerSecond === null ? "—" : `${message.metrics.tokensPerSecond} tok/s`}</MessageFooter>}</MessageContent></Message></MessageGroup></MessageScrollerItem>)}</MessageScrollerContent></MessageScrollerViewport></MessageScroller></MessageScrollerProvider>{error && <p className="text-sm text-destructive" role="alert">{error}</p>}<form className="flex items-end gap-2" onSubmit={submit}><label className="sr-only" htmlFor="try-chat-composer">Message</label><textarea id="try-chat-composer" className="min-h-12 flex-1 resize-y rounded-md border bg-background px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Ask your local AI…" disabled={status === "sending" || status === "streaming"} /><Button type="submit" disabled={!draft.trim() || status === "sending" || status === "streaming"}><Send className="size-4" />Send</Button>{(status === "sending" || status === "streaming") && <Button type="button" variant="outline" size="icon" aria-label="Stop" onClick={stop}><Square className="size-4" /></Button>}</form><p className="text-xs text-muted-foreground">Role: {labelOf(role.id)}. Operator session only; no client key is needed on this computer.</p></CardContent></Card>;
}

function VoiceTab({ role, labelOf, kind }: { role: RoleRecord; labelOf: (id: string) => string; kind: "tts" | "stt" }) {
  const [text, setText] = useState(""); const [audioUrl, setAudioUrl] = useState<string | null>(null); const [recording, setRecording] = useState(false); const recorder = useRef<MediaRecorder | null>(null);
  async function speak() { const response = await fetch("/v1/audio/speech", { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify({ model: "tts", input: text }) }); if (response.ok) setAudioUrl(URL.createObjectURL(await response.blob())); }
  function listen() { if (recording) { recorder.current?.stop(); setRecording(false); return; } if (!navigator.mediaDevices || typeof MediaRecorder === "undefined") return; const chunks: BlobPart[] = []; void navigator.mediaDevices.getUserMedia({ audio: true }).then((stream) => { const next = new MediaRecorder(stream); recorder.current = next; next.ondataavailable = (event) => chunks.push(event.data); next.onstop = async () => { stream.getTracks().forEach((track) => track.stop()); const form = new FormData(); form.append("file", new Blob(chunks, { type: next.mimeType }), "recording.webm"); const response = await fetch("/v1/audio/transcriptions", { method: "POST", credentials: "same-origin", body: form }); if (response.ok) setText((await response.json() as { text?: string }).text ?? ""); }; next.start(); setRecording(true); }); }
  return <Card><CardHeader><CardTitle>{kind === "tts" ? "Speak" : "Listen"}</CardTitle><CardDescription>{kind === "tts" ? "Type a sentence and hear the local voice." : "Record a short sentence and see the words as they return."}</CardDescription></CardHeader><CardContent className="space-y-5">{kind === "tts" ? <><Input value={text} onChange={(event) => setText(event.target.value)} placeholder="Type something to say" /><label className="block space-y-2 text-sm font-medium" htmlFor="try-voice">Voice<select id="try-voice" className="mt-1 h-9 w-full rounded-md border bg-background px-3 text-sm"><option>Default local voice</option></select></label><div className="flex items-center gap-3"><Button variant="outline" onClick={() => void speak()} disabled={!text.trim()}><Volume2 className="size-4" />Play</Button>{audioUrl && <audio controls src={audioUrl}><track kind="captions" srcLang="en" label="Speech" src="data:text/vtt,WEBVTT" /></audio>}</div></> : <><Button variant="outline" onClick={listen}><Mic className="size-4" />{recording ? "Stop recording" : "Record"}</Button><p className="rounded-xl border bg-muted/30 p-5 text-base">{text || "Your words will appear here."}</p></>}<p className="text-xs text-muted-foreground">Role: {labelOf(role.id)}</p></CardContent></Card>;
}

function GeneratorTab({ role, labelOf, acknowledged, onAcknowledge }: { role: RoleRecord; labelOf: (id: string) => string; acknowledged: boolean; onAcknowledge: () => Promise<void> }) {
  const [prompt, setPrompt] = useState(""); const [quality, setQuality] = useState("everyday"); const [ackOpen, setAckOpen] = useState(false); const [sent, setSent] = useState(false);
  async function generate() { if (!acknowledged) { setAckOpen(true); return; } setSent(true); }
  async function accept() { await onAcknowledge(); setAckOpen(false); setSent(true); }
  const label = labelOf(role.id);
  return <><Card><CardHeader><CardTitle>{label}</CardTitle><CardDescription>Stateless generation. The result is not saved.</CardDescription></CardHeader><CardContent className="space-y-5"><Input value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder={`Describe a ${label.toLowerCase()}…`} /><div className="flex flex-wrap items-center gap-3"><label className="text-sm font-medium" htmlFor={`quality-${role.id}`}>Quality</label><select id={`quality-${role.id}`} className="h-9 rounded-md border bg-background px-3 text-sm" value={quality} onChange={(event) => setQuality(event.target.value)}><option>fast</option><option>everyday</option><option>best</option></select><Button variant="outline" onClick={() => void generate()} disabled={!prompt.trim() || !roleReady(role)}>Generate</Button></div>{sent && <p className="rounded-xl border border-dashed p-5 text-base text-muted-foreground">Coming with jobs. The {label} role is wired for a future job response.</p>}{!roleReady(role) && <p className="text-base text-muted-foreground">Coming with jobs. {role.reason ?? "Engine binding is not implemented yet."}</p>}</CardContent></Card><Dialog open={ackOpen} onOpenChange={setAckOpen}><DialogContent><DialogHeader><DialogTitle>Before you generate</DialogTitle><DialogDescription>Generated images, video, and music can be wrong or unexpected. I understand this is AI output and I will review it before I use it.</DialogDescription></DialogHeader><Button onClick={() => void accept()}>I understand</Button></DialogContent></Dialog></>;
}

export function TryItPage({ initialRole = "chat" }: { initialRole?: string } = {}) {
  const roles = useApiResource<{ roles: RoleRecord[] }>("/stack/v1/roles"); const ack = useApiResource<{ acknowledged: boolean }>("/stack/v1/operator/generator-ack"); const [active, setActive] = useState(initialRole);
  const roleMap = useMemo(() => new Map((roles.data?.roles ?? []).map((role) => [role.id, role])), [roles.data]); const labelOf = (id: string) => labelForRole(id, roles.data?.roles); const visible = ["chat", "tts", "stt", "image", "video", "music"].map((id) => roleMap.get(id)).filter((role): role is RoleRecord => !!role);
  async function acknowledge() { await api.post("/stack/v1/operator/generator-ack", { acknowledged: true }); await ack.refetch(); }
  return <main className="mx-auto w-full max-w-5xl space-y-5 px-4 py-5 sm:px-8 lg:py-6"><p className="max-w-2xl text-sm text-muted-foreground">This box forgets when you leave it. For a real assistant that remembers, install MaiPai Home.</p>{roles.loading && <Card><CardContent className="p-6">Loading abilities…</CardContent></Card>}{roles.data && <Tabs value={active} onValueChange={setActive} orientation="vertical" className="grid gap-6 md:grid-cols-[12rem_1fr]"><TabsList variant="line" className="h-fit w-full items-stretch md:flex-col">{visible.map((role) => <TabsTrigger className="justify-start" key={role.id} value={role.id}>{labelOf(role.id)}</TabsTrigger>)}</TabsList>{visible.map((role) => <TabsContent key={role.id} value={role.id}>{role.id === "chat" ? <ChatTab role={role} labelOf={labelOf} /> : role.id === "tts" || role.id === "stt" ? roleReady(role) ? <VoiceTab role={role} labelOf={labelOf} kind={role.id} /> : <OfflineState role={role} labelOf={labelOf} /> : <GeneratorTab role={role} labelOf={labelOf} acknowledged={ack.data?.acknowledged === true} onAcknowledge={acknowledge} />}</TabsContent>)}</Tabs>}</main>;
}
